In [107]:
import pandas as pd

## Data Gathering

In [108]:
train=pd.read_csv('twitter_training.csv')

In [109]:
train

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...
...,...,...,...,...
74676,9200,Nvidia,Positive,Just realized that the Windows partition of my...
74677,9200,Nvidia,Positive,Just realized that my Mac window partition is ...
74678,9200,Nvidia,Positive,Just realized the windows partition of my Mac ...
74679,9200,Nvidia,Positive,Just realized between the windows partition of...
74680,9200,Nvidia,Positive,Just like the windows partition of my Mac is l...

In [110]:
data=train.sample(15000,random_state=42)

In [111]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [112]:
data.shape

(15000, 4)

In [113]:
data['Positive'].value_counts()

Positive
Negative      4488
Positive      4275
Neutral       3568
Irrelevant    2669
Name: count, dtype: int64

In [114]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    151
dtype: int64

In [115]:
data.duplicated().sum()

np.int64(127)

## Data Cleaning

In [116]:
data.shape

(15000, 4)

In [117]:
data.drop_duplicates(inplace=True)

In [118]:
data.duplicated().sum()

np.int64(0)

In [119]:
data.drop(columns=['2401','Borderlands'],inplace=True)

In [120]:
data.head()

         Positive im getting on borderlands and i will murder you all ,
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [121]:
data.rename(columns={'Positive':'Sentiment','im getting on borderlands and i will murder you all ,':'Tweets'},inplace=True)

In [122]:
data

        Sentiment                                             Tweets
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one
...           ...                                                ...
7757     Positive                   i can play overwatch again (bad)
3887     Negative  The base weapons of black ops Cold War are so ...
22629     Neutral  Don'don t just jump me... @CSGO... is medal. t...
66836  Irrelevant  for FUCKS SAKE!!!!!!!! FIRST MONTH FOR ONE MON...
56434    Positive  New video later shoot premiere at 12 and its g...

[14873 rows x 2 columns]

In [123]:
data=data[(data['Sentiment']=='Positive')|(data['Sentiment']=='Negative')|(data['Sentiment']=='Neutral')]

In [124]:
data['Sentiment'].value_counts()

Sentiment
Negative    4453
Positive    4231
Neutral     3546
Name: count, dtype: int64

##

In [125]:
data.isnull().sum()

Sentiment      0
Tweets       103
dtype: int64

In [126]:
data.shape

(12230, 2)

In [129]:
data=data.dropna()

In [130]:
data.isnull().sum()

Sentiment    0
Tweets       0
dtype: int64

In [132]:
data.duplicated().sum()

np.int64(260)

In [133]:
data=data.drop_duplicates()
data=data.dropna()

In [134]:
data.duplicated().sum()

np.int64(0)

In [135]:
data.isnull().sum()

Sentiment    0
Tweets       0
dtype: int64

In [136]:
data.shape

(11867, 2)

## Feature Encoding

In [137]:
from sklearn.preprocessing import LabelEncoder

In [138]:
label=LabelEncoder()

In [139]:
data['Sentiment']=label.fit_transform(data['Sentiment'])

In [140]:
data['Sentiment']

21704    2
47008    0
454      2
58076    0
40659    2
        ..
57537    2
7757     2
3887     0
22629    1
56434    2
Name: Sentiment, Length: 11867, dtype: int64

In [141]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [142]:
tokenizer=Tokenizer(oov_token='Nothing')

In [143]:
tokenizer.fit_on_texts(data['Tweets'])

In [144]:
tokenizer.word_index

{'Nothing': 1,
 'the': 2,
 'i': 3,
 'to': 4,
 'and': 5,
 'a': 6,
 'of': 7,
 'is': 8,
 'in': 9,
 'for': 10,
 'this': 11,
 'it': 12,
 'my': 13,
 'on': 14,
 'you': 15,
 'that': 16,
 'com': 17,
 'game': 18,
 'with': 19,
 'so': 20,
 'be': 21,
 'just': 22,
 'me': 23,
 'have': 24,
 'but': 25,
 'all': 26,
 'not': 27,
 'was': 28,
 'are': 29,
 'at': 30,
 '2': 31,
 'like': 32,
 'out': 33,
 'pic': 34,
 'twitter': 35,
 'your': 36,
 'from': 37,
 'get': 38,
 'now': 39,
 'as': 40,
 'we': 41,
 'good': 42,
 't': 43,
 'play': 44,
 'johnson': 45,
 'they': 46,
 'about': 47,
 'if': 48,
 'can': 49,
 'new': 50,
 'one': 51,
 'an': 52,
 'no': 53,
 'really': 54,
 'when': 55,
 "i'm": 56,
 'will': 57,
 'love': 58,
 'has': 59,
 'up': 60,
 'what': 61,
 'more': 62,
 'do': 63,
 '3': 64,
 'why': 65,
 'unk': 66,
 'still': 67,
 'shit': 68,
 'time': 69,
 "it's": 70,
 'or': 71,
 'co': 72,
 'some': 73,
 'by': 74,
 'been': 75,
 'how': 76,
 'people': 77,
 'https': 78,
 'amazon': 79,
 '’': 80,
 'microsoft': 81,
 'best': 82,
 'games': 83,
 'dead': 84,
 '1': 85,
 'facebook': 86,
 'fucking': 87,
 'playing': 88,
 'got': 89,
 'verizon': 90,
 'because': 91,
 'great': 92,
 'fuck': 93,
 'rhandlerr': 94,
 'go': 95,
 'red': 96,
 'even': 97,
 'please': 98,
 'xbox': 99,
 'who': 100,
 'see': 101,
 'us': 102,
 'home': 103,
 'back': 104,
 'much': 105,
 '5': 106,
 'only': 107,
 'google': 108,
 'going': 109,
 'had': 110,
 'am': 111,
 "can't": 112,
 'fix': 113,
 'nvidia': 114,
 's': 115,
 'borderlands': 116,
 'there': 117,
 'tv': 118,
 'their': 119,
 'would': 120,
 'after': 121,
 'fun': 122,
 'our': 123,
 '4': 124,
 'its': 125,
 'again': 126,
 'these': 127,
 'day': 128,
 'eamaddennfl': 129,
 'than': 130,
 'them': 131,
 'very': 132,
 'over': 133,
 "don't": 134,
 'fifa': 135,
 'today': 136,
 'also': 137,
 'make': 138,
 'wait': 139,
 'never': 140,
 '2020': 141,
 'here': 142,
 'pubg': 143,
 'redemption': 144,
 'then': 145,
 'twitch': 146,
 'know': 147,
 'nba2k': 148,
 'first': 149,
 'want': 150,
 'bad': 151,
 'ever': 152,
 'rainbow6game': 153,
 'think': 154,
 'thank': 155,
 'gta': 156,
 '…': 157,
 'he': 158,
 'every': 159,
 'amazing': 160,
 'depot': 161,
 'work': 162,
 'year': 163,
 'damn': 164,
 'played': 165,
 'ps5': 166,
 'thanks': 167,
 'legends': 168,
 'guys': 169,
 'getting': 170,
 'x': 171,
 'call': 172,
 'i’m': 173,
 'too': 174,
 'most': 175,
 'last': 176,
 'news': 177,
 'video': 178,
 "i've": 179,
 'series': 180,
 'help': 181,
 'any': 182,
 'world': 183,
 'warcraft': 184,
 'happy': 185,
 'down': 186,
 'into': 187,
 'well': 188,
 '10': 189,
 'black': 190,
 'league': 191,
 'v': 192,
 'being': 193,
 'years': 194,
 'u': 195,
 'overwatch': 196,
 'off': 197,
 'man': 198,
 'looks': 199,
 'say': 200,
 'always': 201,
 'watch': 202,
 'right': 203,
 'youtu': 204,
 'another': 205,
 'ghostrecon': 206,
 'live': 207,
 'did': 208,
 'finally': 209,
 'creed': 210,
 'stop': 211,
 'update': 212,
 'need': 213,
 'team': 214,
 'youtube': 215,
 'store': 216,
 'battlefield': 217,
 'actually': 218,
 'players': 219,
 'should': 220,
 'everyone': 221,
 'ass': 222,
 'via': 223,
 'money': 224,
 'made': 225,
 'his': 226,
 'next': 227,
 'fortnite': 228,
 'buy': 229,
 'csgo': 230,
 'while': 231,
 'way': 232,
 'look': 233,
 'big': 234,
 'hearthstone': 235,
 'duty': 236,
 'win': 237,
 'already': 238,
 'many': 239,
 'free': 240,
 'thing': 241,
 'better': 242,
 'could': 243,
 'which': 244,
 'since': 245,
 'take': 246,
 'were': 247,
 'playstation': 248,
 'come': 249,
 'awesome': 250,
 'wtf': 251,
 'it’s': 252,
 'before': 253,
 'support': 254,
 'nice': 255,
 'something': 256,
 'bit': 257,
 'pc': 258,
 'hate': 259,
 'keep': 260,
 'her': 261,
 'playapex': 262,
 'other': 263,
 'online': 264,
 'done': 265,
 'gonna': 266,
 'trying': 267,
 'excited': 268,
 '20': 269,
 'having': 270,
 'ubisoft': 271,
 'ly': 272,
 'wow': 273,
 'days': 274,
 'give': 275,
 'oh': 276,
 'stream': 277,
 'hey': 278,
 'baby': 279,
 'everything': 280,
 'pretty': 281,
 'both': 282,
 '6': 283,
 'cool': 284,
 'lot': 285,
 'looking': 286,
 'old': 287,
 'war': 288,
 'doing': 289,
 'long': 290,
 'account': 291,
 'does': 292,
 'where': 293,
 'top': 294,
 'start': 295,
 'check': 296,
 'life': 297,
 'im': 298,
 'someone': 299,
 'mobile': 300,
 'cyberpunk': 301,
 'through': 302,
 'card': 303,
 'nothing': 304,
 '7': 305,
 'two': 306,
 'player': 307,
 'pay': 308,
 'real': 309,
 'use': 310,
 'things': 311,
 'servers': 312,
 'him': 313,
 'powder': 314,
 'feel': 315,
 'same': 316,
 'dota': 317,
 'super': 318,
 'lol': 319,
 'working': 320,
 'phone': 321,
 'stupid': 322,
 'such': 323,
 'little': 324,
 'night': 325,
 'm': 326,
 'those': 327,
 'hope': 328,
 'service': 329,
 'problem': 330,
 'making': 331,
 'company': 332,
 'season': 333,
 'god': 334,
 'hours': 335,
 'almost': 336,
 'hell': 337,
 'makes': 338,
 'ops': 339,
 'yet': 340,
 'literally': 341,
 'until': 342,
 'week': 343,
 '2077': 344,
 'italy': 345,
 'probably': 346,
 'anyone': 347,
 'dont': 348,
 'miss': 349,
 'favorite': 350,
 'can’t': 351,
 'uk': 352,
 'cold': 353,
 'against': 354,
 '19': 355,
 'won': 356,
 'try': 357,
 'business': 358,
 'hard': 359,
 '100': 360,
 'release': 361,
 "doesn't": 362,
 'whole': 363,
 'absolutely': 364,
 'let': 365,
 'full': 366,
 'own': 367,
 'find': 368,
 'times': 369,
 'worst': 370,
 'gaming': 371,
 'lost': 372,
 'show': 373,
 'chance': 374,
 'trash': 375,
 'said': 376,
 'app': 377,
 'minutes': 378,
 'few': 379,
 'apex': 380,
 'open': 381,
 '0': 382,
 'end': 383,
 'put': 384,
 'says': 385,
 'without': 386,
 'part': 387,
 'story': 388,
 'cant': 389,
 "that's": 390,
 'assassins': 391,
 'hit': 392,
 '2k': 393,
 'mode': 394,
 'interesting': 395,
 'stuff': 396,
 'far': 397,
 'console': 398,
 'using': 399,
 'ea': 400,
 'guy': 401,
 'sure': 402,
 'coming': 403,
 'ranked': 404,
 'wrong': 405,
 'gameplay': 406,
 'idea': 407,
 'callofduty': 408,
 'anything': 409,
 'gets': 410,
 'ban': 411,
 'ps4': 412,
 'tt': 413,
 'around': 414,
 'thought': 415,
 'maybe': 416,
 'order': 417,
 'selling': 418,
 'data': 419,
 '30': 420,
 'reason': 421,
 'vaccine': 422,
 'tell': 423,
 'friends': 424,
 'care': 425,
 '21': 426,
 'screen': 427,
 "you're": 428,
 'beautiful': 429,
 'perfect': 430,
 'soon': 431,
 'crazy': 432,
 'worth': 433,
 'enough': 434,
 '15': 435,
 'used': 436,
 'y’all': 437,
 "y'all": 438,
 'sad': 439,
 'point': 440,
 'pro': 441,
 'covid': 442,
 'madden': 443,
 'though': 444,
 'enjoy': 445,
 'tonight': 446,
 'w': 447,
 'p': 448,
 'd': 449,
 'bought': 450,
 'high': 451,
 'dota2': 452,
 'graphics': 453,
 'went': 454,
 'talc': 455,
 "didn't": 456,
 'away': 457,
 'banned': 458,
 'watching': 459,
 'month': 460,
 'change': 461,
 'weekend': 462,
 'epic': 463,
 'may': 464,
 'system': 465,
 'forward': 466,
 'internet': 467,
 'second': 468,
 '12': 469,
 'playhearthstone': 470,
 'tried': 471,
 'ift': 472,
 'different': 473,
 'bro': 474,
 'feels': 475,
 'kill': 476,
 "i'll": 477,
 "assassin's": 478,
 'price': 479,
 'share': 480,
 'broken': 481,
 'based': 482,
 'due': 483,
 'latest': 484,
 'saying': 485,
 'grand': 486,
 'org': 487,
 'cause': 488,
 '”': 489,
 'able': 490,
 'job': 491,
 'don’t': 492,
 'ok': 493,
 'pre': 494,
 'patch': 495,
 'took': 496,
 'comes': 497,
 'cs': 498,
 'skin': 499,
 'character': 500,
 'definitely': 501,
 'ago': 502,
 'morning': 503,
 'server': 504,
 'mean': 505,
 'myself': 506,
 'homedepot': 507,
 'exciting': 508,
 'sorry': 509,
 'power': 510,
 'else': 511,
 'huge': 512,
 'terrible': 513,
 'myteam': 514,
 'wanna': 515,
 'n2k': 516,
 'instead': 517,
 'might': 518,
 'problems': 519,
 'cod': 520,
 'level': 521,
 'post': 522,
 'came': 523,
 'sucks': 524,
 'gold': 525,
 'i’ve': 526,
 'started': 527,
 'beluba': 528,
 'must': 529,
 'net': 530,
 'apps': 531,
 'cards': 532,
 'read': 533,
 'rewards': 534,
 'content': 535,
 'finished': 536,
 'customer': 537,
 'anymore': 538,
 'products': 539,
 'she': 540,
 'wanted': 541,
 'windows': 542,
 'during': 543,
 'guess': 544,
 'music': 545,
 '8': 546,
 'seems': 547,
 'event': 548,
 'leagueoflegends': 549,
 'updates': 550,
 'months': 551,
 'luck': 552,
 'fact': 553,
 'ready': 554,
 'seen': 555,
 'needs': 556,
 'killed': 557,
 'tomorrow': 558,
 'dlvr': 559,
 'set': 560,
 '9': 561,
 'run': 562,
 'match': 563,
 'y': 564,
 'achievement': 565,
 'trailer': 566,
 'annoying': 567,
 'experience': 568,
 'later': 569,
 're': 570,
 'talk': 571,
 'remember': 572,
 'single': 573,
 "won't": 574,
 'r': 575,
 'die': 576,
 'holy': 577,
 'shot': 578,
 'seriously': 579,
 'name': 580,
 'error': 581,
 'list': 582,
 'design': 583,
 'ronnie2k': 584,
 'early': 585,
 'breakpoint': 586,
 'half': 587,
 '3080': 588,
 'hi': 589,
 'yo': 590,
 'hour': 591,
 'health': 592,
 'yall': 593,
 'honestly': 594,
 'least': 595,
 'gone': 596,
 'rtx': 597,
 'three': 598,
 'found': 599,
 'edition': 600,
 "haven't": 601,
 'buying': 602,
 'number': 603,
 'completely': 604,
 'face': 605,
 'loved': 606,
 'warzone': 607,
 'place': 608,
 'blizzard': 609,
 'sometimes': 610,
 'late': 611,
 'gen': 612,
 'easports': 613,
 'once': 614,
 'community': 615,
 'earned': 616,
 'person': 617,
 'c': 618,
 'yes': 619,
 'e': 620,
 'videos': 621,
 'proud': 622,
 'believe': 623,
 'issue': 624,
 'book': 625,
 'class': 626,
 '•': 627,
 'issues': 628,
 'apple': 629,
 'together': 630,
 'hear': 631,
 'seeing': 632,
 'funny': 633,
 'don': 634,
 'teams': 635,
 'totally': 636,
 'small': 637,
 'called': 638,
 'movie': 639,
 'friend': 640,
 'keeps': 641,
 'fan': 642,
 'omg': 643,
 'birthday': 644,
 'access': 645,
 'pass': 646,
 'thinking': 647,
 'suck': 648,
 'bullshit': 649,
 'each': 650,
 'follow': 651,
 'code': 652,
 'city': 653,
 'hello': 654,
 'worse': 655,
 'ghost': 656,
 'review': 657,
 'complete': 658,
 'less': 659,
 'kinda': 660,
 'major': 661,
 'released': 662,
 'retweet': 663,
 'under': 664,
 'sound': 665,
 'trump': 666,
 'switch': 667,
 'sick': 668,
 'canada': 669,
 'battle': 670,
 'leave': 671,
 'past': 672,
 'smh': 673,
 'streaming': 674,
 'either': 675,
 'tech': 676,
 'bugs': 677,
 'understand': 678,
 'launch': 679,
 'incredible': 680,
 'join': 681,
 'india': 682,
 'tired': 683,
 'million': 684,
 'main': 685,
 "they're": 686,
 'daily': 687,
 'gotta': 688,
 '“': 689,
 'article': 690,
 'lmao': 691,
 'kills': 692,
 'running': 693,
 'cannot': 694,
 'link': 695,
 'yesterday': 696,
 'saw': 697,
 'odyssey': 698,
 'ai': 699,
 'action': 700,
 'instagram': 701,
 'deal': 702,
 'add': 703,
 'move': 704,
 'cute': 705,
 'received': 706,
 'bring': 707,
 'stock': 708,
 'gift': 709,
 'mind': 710,
 'joke': 711,
 'iphone': 712,
 'b': 713,
 'family': 714,
 'market': 715,
 'waiting': 716,
 'garbage': 717,
 "we're": 718,
 'starting': 719,
 'kind': 720,
 'slow': 721,
 'mad': 722,
 'house': 723,
 've': 724,
 'stay': 725,
 'global': 726,
 "what's": 727,
 'ubisoftsupport': 728,
 'means': 729,
 "let's": 730,
 'drop': 731,
 'moment': 732,
 'girl': 733,
 'entire': 734,
 'franchise': 735,
 'that’s': 736,
 'goes': 737,
 'moments': 738,
 'fps': 739,
 'technology': 740,
 'truly': 741,
 'playoverwatch': 742,
 'points': 743,
 'absolute': 744,
 'glad': 745,
 'rockstargames': 746,
 'social': 747,
 'tho': 748,
 'spent': 749,
 'id': 750,
 'page': 751,
 'line': 752,
 'currently': 753,
 'quite': 754,
 'warfare': 755,
 'coronavirus': 756,
 'hyped': 757,
 'weeks': 758,
 'o': 759,
 'insane': 760,
 'bug': 761,
 'original': 762,
 'car': 763,
 '14': 764,
 'ur': 765,
 'steam': 766,
 'history': 767,
 'cancer': 768,
 'special': 769,
 'item': 770,
 'left': 771,
 'users': 772,
 'hot': 773,
 'trust': 774,
 'sounds': 775,
 'sell': 776,
 '–': 777,
 'continue': 778,
 'j': 779,
 'close': 780,
 'okay': 781,
 'congratulations': 782,
 'decided': 783,
 'boy': 784,
 'easy': 785,
 'delayed': 786,
 'talking': 787,
 'break': 788,
 'final': 789,
 'fortnitegame': 790,
 'taking': 791,
 'toxic': 792,
 'pick': 793,
 'version': 794,
 'star': 795,
 'lots': 796,
 'walmart': 797,
 'women': 798,
 'sold': 799,
 'takes': 800,
 'wikipedia': 801,
 'turn': 802,
 'dear': 803,
 'crap': 804,
 'yeah': 805,
 'sony': 806,
 "there's": 807,
 'happened': 808,
 'kids': 809,
 'siege': 810,
 'welcome': 811,
 'decision': 812,
 'en': 813,
 'hero': 814,
 'ridiculous': 815,
 'modern': 816,
 'including': 817,
 'men': 818,
 'paid': 819,
 'knows': 820,
 'performance': 821,
 'told': 822,
 '99': 823,
 'enjoyed': 824,
 '24': 825,
 'redeeming': 826,
 'fans': 827,
 'connection': 828,
 'shooting': 829,
 'wins': 830,
 'digital': 831,
 'report': 832,
 'worked': 833,
 'safe': 834,
 'mut': 835,
 'bitch': 836,
 'services': 837,
 'l': 838,
 'date': 839,
 'head': 840,
 'massive': 841,
 'feeling': 842,
 'plus': 843,
 'geforce': 844,
 'true': 845,
 'packs': 846,
 'works': 847,
 'box': 848,
 'wild': 849,
 'forever': 850,
 'heart': 851,
 'death': 852,
 'biggest': 853,
 'f': 854,
 'security': 855,
 'nba': 856,
 'shut': 857,
 'yourself': 858,
 'low': 859,
 'longer': 860,
 'died': 861,
 'dope': 862,
 'sense': 863,
 'beta': 864,
 'created': 865,
 'fight': 866,
 'stuck': 867,
 'fast': 868,
 'stopped': 869,
 'felt': 870,
 'china': 871,
 'channel': 872,
 'plan': 873,
 'boring': 874,
 'art': 875,
 'plz': 876,
 '11': 877,
 'state': 878,
 'gpu': 879,
 'unit': 880,
 'nfl': 881,
 'school': 882,
 'n': 883,
 'search': 884,
 'learning': 885,
 'listen': 886,
 'ordered': 887,
 'important': 888,
 'drive': 889,
 'sweet': 890,
 'hand': 891,
 'hold': 892,
 'somehow': 893,
 'test': 894,
 'plays': 895,
 'skins': 896,
 'platform': 897,
 'delivery': 898,
 'heard': 899,
 'current': 900,
 'email': 901,
 'option': 902,
 'developers': 903,
 'between': 904,
 'football': 905,
 '13': 906,
 'till': 907,
 'cry': 908,
 'powerful': 909,
 'map': 910,
 'lose': 911,
 'enjoying': 912,
 'spend': 913,
 'rather': 914,
 'wish': 915,
 'future': 916,
 'crashing': 917,
 'ya': 918,
 '000': 919,
 'valorant': 920,
 'racist': 921,
 '60': 922,
 'rt': 923,
 'summoners': 924,
 'word': 925,
 'demon': 926,
 'favourite': 927,
 'pls': 928,
 'matter': 929,
 'fixed': 930,
 'controller': 931,
 'quit': 932,
 'bc': 933,
 'recon': 934,
 'rest': 935,
 'log': 936,
 'couple': 937,
 'chinese': 938,
 'tf': 939,
 'giving': 940,
 'government': 941,
 '50': 942,
 'inside': 943,
 'ppl': 944,
 'eahelp': 945,
 'despite': 946,
 'dark': 947,
 'behind': 948,
 'calling': 949,
 'theft': 950,
 '25': 951,
 'calls': 952,
 '16': 953,
 'especially': 954,
 'companies': 955,
 'greatest': 956,
 'within': 957,
 'website': 958,
 'random': 959,
 'white': 960,
 'brand': 961,
 'sales': 962,
 'suddenly': 963,
 'imagine': 964,
 'fantastic': 965,
 'control': 966,
 'party': 967,
 'program': 968,
 'gave': 969,
 'fake': 970,
 'cuz': 971,
 'towards': 972,
 'king': 973,
 'decent': 974,
 'edge': 975,
 'quality': 976,
 'tweet': 977,
 'shitty': 978,
 'ahead': 979,
 'pandemic': 980,
 'trial': 981,
 'short': 982,
 'monday': 983,
 'create': 984,
 'customers': 985,
 'ball': 986,
 'happens': 987,
 "isn't": 988,
 'features': 989,
 'explain': 990,
 'af': 991,
 'dumb': 992,
 'finish': 993,
 'g': 994,
 'poor': 995,
 'speed': 996,
 'li': 997,
 'showing': 998,
 'row': 999,
 'download': 1000,
 ...}

In [145]:
tokenizer.word_counts

OrderedDict([('yo', 51),
             ('this', 2397),
             ('looks', 180),
             ('lit', 14),
             ('team', 167),
             ('go', 352),
             ('overwatch', 182),
             ('combo', 8),
             ('pay', 111),
             ('attention', 10),
             ('executive', 4),
             ('administrators', 4),
             ('while', 157),
             ('your', 723),
             ('stores', 26),
             ('are', 909),
             ('taking', 35),
             ('delivery', 30),
             ('orders', 19),
             ('for', 2541),
             ('pallets', 2),
             ('of', 3137),
             ('bricks', 2),
             ('to', 4696),
             ('downtown', 2),
             ('then', 243),
             ('you', 1910),
             ('were', 145),
             ('being', 185),
             ('used', 72),
             ('in', 2554),
             ('helping', 24),
             ('the', 7089),
             ('destruction', 5),
             ('private', 10),
             ('property', 6),
             ('one', 556),
             ('rainbow6game', 231),
             ('server', 61),
             ('available', 26),
             ('xbox', 342),
             ('🥺', 9),
             ('so', 1272),
             ('awesome', 141),
             ('siege', 34),
             ('attempt', 6),
             ('strangest', 3),
             ('bleeding', 4),
             ('out', 743),
             ('spinning', 8),
             ('sequence', 2),
             ('ever', 232),
             ('s', 293),
             ('my', 2006),
             ('first', 238),
             ('squadmate', 1),
             ('john', 14),
             ('could', 151),
             ('see', 334),
             ('exactly', 16),
             ('which', 151),
             ('was', 918),
             ("i'm", 524),
             ('really', 528),
             ('looking', 122),
             ('forward', 67),
             ('game', 1503),
             ('verizon', 366),
             ('sheds', 1),
             ('81', 4),
             ('000', 29),
             ('digital', 33),
             ('tv', 285),
             ('on', 1972),
             ('black', 188),
             ('cutting', 8),
             ('escalates', 1),
             ('breitbart', 2),
             ('com', 1585),
             ('entertainment', 13),
             ('internet', 67),
             ('gave', 27),
             ('way', 157),
             ('coke', 3),
             ('show', 87),
             ('money', 160),
             ('keep', 135),
             ('ch', 2),
             ('tmmobile', 1),
             ('guys', 209),
             ('very', 261),
             ('slow', 39),
             ('town', 12),
             ('tuba', 2),
             ('fix', 302),
             ('fucking', 374),
             ('pro', 71),
             ('am', 311),
             ('can’t', 96),
             ('find', 90),
             ('no', 530),
             ('games', 382),
             ('2ksupport', 22),
             ('i', 4911),
             ('love', 523),
             ('how', 439),
             ('gives', 20),
             ('each', 45),
             ('a', 3893),
             ('new', 568),
             ('loot', 22),
             ('box', 32),
             ('playing', 374),
             ('support', 139),
             ('forgot', 26),
             ('when', 528),
             ('hated', 7),
             ('who', 341),
             ('mad', 39),
             ('about', 580),
             ('dame', 10),
             ('getting', 208),
             ('itself', 23),
             ('regular', 9),
             ('cover', 16),
             ('like', 744),
             ('kobe', 8),
             ('or', 449),
             ('get', 685),
             ('its', 277),
             ('legend', 21),
             ('edition', 50),
             ('unk', 471),
             ('disrespect', 8),
             ('y’all', 72),
             ('showed', 17),
             ('wild', 32),
             ('simpletons', 1),
             ('only', 320),
             ('lol', 106),
             ("here's", 14),
             ('montage', 6),
             ('rescuing', 1),
             ('teammate', 14),
             ('spreadlovehxly', 2),
             ('few', 86),
             ('times', 90),
             ('other', 134),
             ('day', 273),
             ('they', 593),
             ('will', 524),
             ('forever', 32),
             ('be', 1127),
             ('heart', 32),
             ('but', 963),
             ('do', 499),
             ('kinda', 44),
             ('tho', 38),
             ('5', 321),
             ('friends', 74),
             ('players', 165),
             ('pokemon', 13),
             ('borderlands', 292),
             ('p', 70),
             ('much', 322),
             ('all', 936),
             ('sims', 5),
             ('6', 123),
             ("haven't", 50),
             ('played', 216),
             ('spiderman', 3),
             ('2', 751),
             ('reignited', 1),
             ('uuuh', 2),
             ("that'm", 1),
             ('not', 921),
             ('through', 114),
             ('with', 1441),
             ('either', 43),
             ('ciaranstrange', 3),
             ('sasspiria', 1),
             ('playstation', 145),
             ('bleh', 2),
             ('holy', 52),
             ('shit', 458),
             ('what', 508),
             ('world', 198),
             ('we', 629),
             ('omg', 46),
             ('dreamcatcher', 1),
             ('x', 208),
             ('league', 188),
             ('federals', 1),
             ('cruises', 1),
             ('paybackindia', 2),
             ('50', 28),
             ('it', 2339),
             ('also', 250),
             ('received', 40),
             ('an', 537),
             ('amazon', 404),
             ('e', 48),
             ('voucher', 6),
             ('offering', 4),
             ('inr', 2),
             ('500', 15),
             ('as', 636),
             ('payback', 6),
             ('rewards', 57),
             ('if', 579),
             ('don’t', 63),
             ('come', 144),
             ('ain’t', 13),
             ('buying', 50),
             ('china', 31),
             ('closes\xa0foxconn', 1),
             ('johnson', 607),
             ('and', 4342),
             ('samsung', 20),
             ('factories', 8),
             ('amid', 10),
             ('virus', 23),
             ('outbreak\xa0', 1),
             ('libertarianhub', 2),
             ('2020', 246),
             ('01', 23),
             ('27', 7),
             ('chi…', 1),
             ('https', 407),
             ('t', 613),
             ('co', 449),
             ('cltmh7bc2m', 2),
             ('just', 1125),
             ('spent', 38),
             ('hour', 51),
             ('at', 793),
             ('home', 323),
             ('depot', 218),
             ('renovating', 1),
             ('house', 39),
             ('expensive', 21),
             ('hell', 100),
             ('closer', 6),
             ('birthday', 46),
             ('cool', 123),
             ('exhausted', 7),
             ('from', 717),
             ('work', 218),
             ('week', 99),
             ('probably', 98),
             ('stream', 127),
             ('today', 251),
             ('i’m', 206),
             ('stoked', 4),
             ('ok', 63),
             ('dont', 97),
             ('care', 74),
             ('charge', 14),
             ('me', 1110),
             ('70', 26),
             ('too', 206),
             ('toxic', 35),
             ('masculinity', 4),
             ('sent', 26),
             ('specifically', 1),
             ('searching', 9),
             ('“men’s', 2),
             ('hair', 16),
             ('again', 276),
             ('d', 70),
             ('mean', 61),
             ('midterms', 2),
             ('because', 363),
             ('it’s', 140),
             ('late', 49),
             ('tired', 42),
             ('atvi', 3),
             ('update', 170),
             ('their', 284),
             ('most', 206),
             ('popular', 7),
             ('hearthstone', 156),
             ('is', 2860),
             ('investors', 11),
             ('should', 163),
             ('satisfied', 7),
             ('amount', 19),
             ('things', 110),
             ('company', 101),
             ('doing', 121),
             ('make', 250),
             ('more', 501),
             ('every', 221),
             ('happy', 194),
             ('enthusiastic', 4),
             ('jerseyboys', 1),
             ('now', 682),
             ('represented', 1),
             ('fb', 15),
             ('welcome', 34),
             ('chucky', 1),
             ('csgo', 158),
             ('our', 278),
             ('chef', 1),
             ('offer', 23),
             ('content', 57),
             ('various', 6),
             ('such', 105),
             ('warcraft', 197),
             ('cs', 62),
             ('valorant', 29),
             ('click', 26),
             ('here', 244),
             ('channel', 31),
             ('tinyurl', 12),
             ('y5gm9h74', 1),
             ('«', 9),
             ('weapon', 19),
             ('development', 9),
             ('sunsetting', 1),
             ('systems', 11),
             ('best', 387),
             ('news', 204),
             ("i've", 201),
             ('heard', 30),
             ('long', 121),
             ('time', 458),
             ('those', 103),
             ('that', 1653),
             ('play', 611),
             ('any', 200),
             ('multi', 4),
             ('major', 44),
             ('season', 101),
             ('strategy', 7),
             ('plan', 31),
             ('involved', 6),
             ('know', 240),
             ('transformation', 1),
             ('needed', 25),
             ('can', 573),
             ('relate', 2),
             ('glorious', 5),
             ('days', 129),
             ('mtg', 5),
             ('bring', 40),
             ('versatile', 3),
             ('creative', 8),
             ('builds', 1),
             ('problems', 59),
             ('sexual', 4),
             ('assaults', 1),
             ('educational', 3),
             ('institutions', 1),
             ('pia', 1),
             ('fake', 27),
             ('licenses', 2),
             ('baloch', 1),
             ('students', 19),
             ('arrested', 3),
             ('protested', 1),
             ('against', 95),
             ('inaccessibility', 1),
             ('215k', 1),
             ('corona', 9),
             ('cases', 5),
             ('rising', 7),
             ('christian', 2),
             ('man', 181),
             ('shot', 52),
             ('he', 224),
             ('had', 318),
             ('bought', 70),
             ('muslim', 2),
             ('majority', 2),
             ('steps', 8),
             ('taken', 21),
             ('ban', 77),
             ('pubg', 244),
             ('3', 484),
             ('these', 274),
             ('even', 347),
             ('wore', 4),
             ('tannis', 2),
             ('her', 135),
             ('handsome', 8),
             ('jack', 10),
             ('want', 236),
             ('report', 33),
             ('racist', 29),
             ('uses', 8),
             ('vile', 2),
             ('words', 13),
             ('harass', 2),
             ('legends', 213),
             ("person's", 3),
             ('id', 38),
             ('gotcha', 2),
             ('uwu', 8),
             ('xd', 19),
             ('20', 131),
             ('series', 201),
             ('dlss', 1),
             ('0', 85),
             ('graphics', 69),
             ('processors', 2),
             ('run', 54),
             ('4k', 14),
             ('speeds', 13),
             ('than', 267),
             ('60', 29),
             ('frames', 4),
             ('per', 20),
             ('second', 67),
             ('according', 6),
             ('nvidia', 300),
             ('pcg', 1),
             ('au', 10),
             ('death', 32),
             ('stran', 1),
             ('why', 475),
             ('two', 112),
             ('year', 218),
             ('old', 122),
             ('them', 267),
             ('same', 108),
             ('youtube', 167),
             ('videos', 48),
             ('ten', 14),
             ('after', 279),
             ('bored', 12),
             ('assassins', 83),
             ('creed', 171),
             ('12', 67),
             ('great', 362),
             ('finished', 57),
             ('off', 182),
             ('last', 205),
             ('red', 350),
             ('dead', 382),
             ('redemption', 244),
             ('legendary', 22),
             ('animal', 17),
             ('pre', 63),
             ('epilogue', 2),
             ('good', 625),
             ('style', 7),
             ('pic', 741),
             ('twitter', 730),
             ('uyo0gbr2bd', 1),
             ('never', 248),
             ('miss', 97),
             ('follow', 45),
             ('current', 30),
             ('updates', 55),
             ('tech', 43),
             ('covid', 71),
             ('19', 95),
             ('comments', 17),
             ('etc', 20),
             ('exc', 1),
             ('playhearthstone', 67),
             ('legit', 14),
             ('disable', 10),
             ('djinn', 1),
             ('asap', 4),
             ('crony', 1),
             ('lame', 11),
             ('boring', 31),
             ('duvalmagic', 8),
             ('gearboxofficial', 23),
             ('wanted', 56),
             ('say', 180),
             ('saying', 64),
             ('huge', 60),
             ('thank', 227),
             ('worked', 33),
             ('working', 106),
             ('wheels', 3),
             ('gearbox', 7),
             ('’', 401),
             ('ve', 39),
             ('been', 443),
             ('crushing', 8),
             ('enven', 2),
             ('months', 55),
             ('before', 140),
             ('knowing', 17),
             ('must', 58),
             ('have', 1068),
             ('real', 111),
             ('difficult', 17),
             ('biggest', 32),
             ('fifa', 253),
             ('21', 74),
             ('downgrades', 1),
             ('⏬', 1),
             ('1', 381),
             ('collab', 2),
             ('f', 32),
             ('sebfut', 1),
             ('waht', 3),
             ('kill', 66),
             ('store', 167),
             ("it's", 456),
             ('five', 22),
             ('kid', 10),
             ('microsoft', 397),
             ('wants', 23),
             ('backwards', 5),
             ('compatible', 15),
             ('console', 81),
             ('mobilesyrup', 2),
             ('05', 20),
             ('28', 20),
             ('mic…', 3),
             ('�', 4),
             ('switched', 11),
             ('got', 371),
             ('galaxy', 6),
             ('note20', 1),
             ('ultra', 10),
             ('decision', 34),
             ('made', 160),
             ("y'all", 72),
             ("ain't", 9),
             ('help', 201),
             ('bokchoy', 1),
             ('request', 16),
             ('forget', 17),
             ('gonna', 133),
             ('google', 320),
             ('tube', 1),
             ('cook', 3),
             ('nasty', 10),
             ('kissing', 1),
             ('rt', 29),
             ('cragon', 1),
             ('myself', 61),
             ('dracula', 1),
             ('masquerade', 2),
             ('origins', 10),
             ('deus', 1),
             ('ex', 12),
             ('human', 21),
             ('revolution', 2),
             ('harry', 3),
             ('breath', 8),
             ('og', 9),
             ('leisure', 1),
             ('suit', 8),
             ('corps', 4),
             ("don't", 254),
             ('judge', 7),
             ('fluffbrawl', 1),
             ('killerxkween91', 1),
             ('itslexitaylor', 1),
             ('jbirdsgaming', 1),
             ('wtty', 1),
             ('gamewrexham', 2),
             ('gamedigital', 2),
             ('email', 30),
             ('stay', 39),
             ('safe', 33),
             ('thanks', 214),
             ('industry', 11),
             ('uk', 96),
             ('restart', 21),
             ('by', 444),
             ('9th', 4),
             ('gen', 49),
             ('still', 460),
             ('iffy', 2),
             ('malphite', 2),
             ('shard', 3),
             ('art', 31),
             ('war', 122),
             ('monolith', 2),
             ('always', 180),
             ('hard', 94),
             ('pick', 35),
             ('attack', 17),
             ('physical', 9),
             ('defense', 26),
             ('magic', 21),
             ('difficulty', 9),
             ('life', 116),
             ('give', 129),
             ('700', 5),
             ('bad', 233),
             ("can't", 305),
             ('dang', 12),
             ('thing', 153),
             ('stock', 40),
             ('plz', 31),
             ('bleepincomputer', 1),
             ('flash', 7),
             ('released', 44),
             ('security', 32),
             ("mysterious'spoofing", 1),
             ("virus'", 1),
             ('windows', 56),
             ('11', 31),
             ('tracked', 1),
             ('cve', 2),
             ('1464', 1),
             ('mention', 14),
             ('discovered', 10),
             ('version', 35),
             ('acknowledgement', 2),
             ('page', 38),
             ('ir', 1),
             ('msrc', 1),
             ('en', 34),
             ('us', 329),
             ('security…', 1),
             ('…', 225),
             ('youre', 7),
             ('throttling', 4),
             ('shame', 25),
             ('schooling', 2),
             ('people', 426),
             ('option', 30),
             ('nothing', 113),
             ("nvidia's", 14),
             ('shares', 11),
             ('rises', 5),
             ('toward', 3),
             ('record', 12),
             ('high', 70),
             ('bernstein', 1),
             ('turns', 13),
             ('bullish', 2),
             ('cuts', 3),
             ('price', 65),
             ('target', 18),
             ('mktw', 2),
             ('net', 58),
             ('32fx3km', 1),
             ('initial', 5),
             ('state', 31),
             ('alabama', 1),
             ('blank', 8),
             ('im', 116),
             ('wasting', 8),
             ('dota', 108),
             ('chick', 4),
             ('insane', 37),
             ('makes', 100),
             ('upgrade', 19),
             ('gpu', 31),
             ('video', 204),
             ('inside', 28),
             ('crashes', 25),
             ('would', 284),
             ('call', 207),
             ('videogamecrashception', 2),
             ('need', 169),
             ('leo', 4),
             ('youtu', 177),
             ('h9jup8kt9wu', 3),
             ('beautiful', 73),
             ('online', 134),
             ('order', 76),
             ('homedepot', 61),
             ('perfect', 73),
             ('→', 7),
             ('eljeeeey', 1),
             ('entering', 22),
             ('grand', 64),
             ('summoners', 29),
             ('watch', 179),
             ('won', 95),
             ('100', 94),
             ('gift', 40),
             ('card', 114),
             ('retweet', 44),
             ('everyday', 21),
             ('another', 176),
             ('chance', 87),
             ('win', 155),
             ('gs', 20),
             ('global', 39),
             ('free', 154),
             ('golden', 25),
             ('kamuy', 7),
             ('unit', 31),
             ('ylnbixjdii', 1),
             ('tile', 3),
             ('enjoyable', 9),
             ('wonderful', 19),
             ('hotel', 4),
             ('throughout', 12),
             ('madden', 71),
             ('nfl', 31),
             ('4', 278),
             ('ps4', 77),
             ('39', 6),
             ('95', 7),
             ('ebay', 21),

In [146]:
tokenizer.document_count

11867

In [148]:
len(tokenizer.word_index) ## Vocanulary size

17872

In [149]:
sequences=tokenizer.texts_to_sequences(data['Tweets'])

In [150]:
sequences

[[590, 11, 199, 1676, 214, 95, 196, 2523],
 [308,
  2159,
  4021,
  4022,
  231,
  36,
  1001,
  29,
  791,
  898,
  1324,
  10,
  6516,
  7,
  6517,
  4,
  6518,
  145,
  15,
  247,
  193,
  436,
  9,
  1075,
  2,
  3481,
  7,
  2160,
  3095],
 [51],
 [153, 504, 29, 1002, 9, 99, 2321],
 [20,
  250,
  810,
  3096,
  4868,
  4023,
  33,
  2524,
  6519,
  152,
  115,
  13,
  149,
  10123,
  1677,
  243,
  101,
  2,
  2524,
  1516,
  244,
  28,
  250],
 [56, 54, 286, 466, 4, 2, 18],
 [90,
  10124,
  4024,
  919,
  831,
  118,
  14,
  2,
  190,
  2525,
  10125,
  6520,
  17,
  1771,
  190,
  467,
  90,
  969,
  232,
  4,
  4869,
  373,
  36,
  224,
  4,
  90,
  260,
  14,
  2525,
  2,
  6521],
 [10126, 15, 169, 29, 132, 721, 9, 2, 1882, 7, 6522],
 [113, 2, 87, 441, 111, 351, 368, 53, 83, 1163],
 [3, 58, 76, 196, 1256, 15, 650, 6, 50, 1164, 848, 10, 88, 254],
 [1003, 55, 3, 2790, 196],
 [100,
  467,
  28,
  722,
  47,
  2161,
  170,
  1116,
  2322,
  1517,
  32,
  2526,
  71,
  38,
  125,
  1203,
  600,
  66,
  66,
  2,
  2527,
  437,
  1454,
  2161,
  28,
  849,
  10127,
  107,
  319],
 [1678, 13, 3097, 7, 10128, 13, 1679, 6523, 6, 379, 369, 2, 263, 128],
 [46, 57, 850, 21, 9, 13, 851, 25, 11, 63, 66, 286, 660, 1676, 748, 66],
 [106,
  424,
  106,
  219,
  1772,
  116,
  448,
  105,
  26,
  3482,
  283,
  601,
  165,
  9,
  850,
  748,
  4870,
  283,
  31,
  10129,
  6524,
  10130,
  27,
  302,
  19,
  11,
  675,
  4871,
  99,
  10131,
  248,
  6525],
 [577, 68, 61, 183, 100, 41, 9],
 [643, 13, 10132, 171, 191, 7, 10133, 10134],
 [6526, 942, 12, 137, 706, 52, 79, 620, 3098, 4025, 6527, 1585, 40, 3099, 534],
 [48, 15, 492, 249, 33, 19, 6, 2526, 600, 3, 1773, 602, 15],
 [871,
  10135,
  45,
  45,
  5,
  1257,
  2528,
  2162,
  1117,
  10136,
  6528,
  17,
  141,
  1118,
  2791,
  10137,
  78,
  43,
  72,
  6529],
 [22, 749, 52, 591, 30, 103, 161, 10138, 2, 723, 1204, 40, 337],
 [3100, 4, 13, 644, 56, 284, 19, 11],
 [3,
  111,
  20,
  2792,
  37,
  162,
  11,
  343,
  193,
  346,
  53,
  116,
  277,
  136,
  173,
  20,
  4026],
 [125, 493, 348, 425, 5, 1680, 23, 1004, 9, 18, 5, 10, 100, 174],
 [792, 4027, 1005, 23, 10139, 2323, 6530, 1518, 126, 14, 79],
 [88, 449],
 [66, 505, 6531, 91, 252, 611, 5, 173, 683],
 [4872,
  2,
  50,
  212,
  10,
  51,
  7,
  119,
  175,
  2793,
  83,
  235,
  8,
  250,
  2008,
  220,
  21,
  2794,
  19,
  2,
  1325,
  7,
  311,
  2,
  332,
  8,
  289,
  4,
  138,
  2,
  219,
  100,
  29,
  170,
  62,
  5,
  62,
  159,
  128,
  185,
  5,
  4028,
  47,
  2,
  18],
 [2,
  10140,
  214,
  8,
  39,
  137,
  10141,
  30,
  1586,
  811,
  10142,
  230,
  123,
  10143,
  57,
  1119,
  15,
  535,
  37,
  3101,
  83,
  323,
  40,
  183,
  7,
  184,
  498,
  95,
  71,
  920,
  14,
  1586,
  1006,
  142,
  10,
  2,
  872,
  1883,
  17,
  10144],
 [2324,
  1326,
  2325,
  10145,
  2009,
  8,
  346,
  2,
  82,
  177,
  179,
  899,
  9,
  6,
  290,
  69,
  327,
  7,
  15,
  16,
  44,
  182,
  4029,
  661,
  333,
  18,
  19,
  182,
  2795,
  873,
  3102,
  220,
  147,
  16,
  11,
  10146,
  8,
  1034,
  40,
  3,
  49,
  6532,
  11,
  4,
  13,
  3483,
  274,
  7,
  88,
  3484,
  5,
  235,
  11,
  57,
  707,
  62,
  4873,
  2529,
  10147,
  5],
 [519,
  849,
  4030,
  10148,
  9,
  4874,
  10149,
  10150,
  970,
  6533,
  10151,
  1327,
  4875,
  91,
  46,
  10152,
  354,
  2,
  10153,
  7,
  2,
  467,
  10154,
  2326,
  3485,
  2796,
  6534,
  198,
  578,
  91,
  158,
  110,
  450,
  6,
  723,
  9,
  6535,
  6536,
  2530,
  1205,
  411,
  143],
 [26,
  64,
  7,
  127,
  29,
  23,
  3,
  97,
  4031,
  6537,
  5,
  261,
  2531,
  2163,
  37,
  2,
  116,
  30],
 [3,
  150,
  4,
  832,
  6,
  921,
  100,
  2532,
  6538,
  921,
  1774,
  4,
  6539,
  23,
  9,
  2,
  191,
  7,
  168,
  18,
  16,
  4876,
  750,
  8,
  6540,
  2533,
  1328],
 [650,
  7,
  2,
  269,
  180,
  10155,
  31,
  382,
  453,
  6541,
  49,
  562,
  9,
  1681,
  30,
  1775,
  7,
  62,
  130,
  922,
  4032,
  1258,
  468,
  3103,
  4,
  114,
  10156,
  17,
  2164,
  852,
  10157],
 [23,
  3,
  492,
  38,
  65,
  13,
  306,
  163,
  287,
  49,
  44,
  131,
  316,
  215,
  621,
  1682,
  369,
  121,
  6,
  163,
  5,
  27,
  38,
  1884,
  137,
  23,
  391,
  210,
  469,
  199,
  92],
 [536,
  197,
  2,
  176,
  96,
  84,
  144,
  31,
  1165,
  1455,
  494,
  6542,
  42,
  4,
  95,
  33,
  9,
  2797,
  34,
  35,
  17,
  10158],
 [140,
  150,
  4,
  349,
  159,
  212,
  651,
  302,
  10,
  900,
  177,
  550,
  676,
  442,
  355,
  1456,
  1259,
  10159],
 [470,
  1683,
  15,
  49,
  2165,
  169,
  10160,
  4033,
  22,
  88,
  10,
  6,
  10161,
  8,
  40,
  2010,
  40,
  12,
  8,
  874],
 [116,
  2534,
  1120,
  3,
  22,
  541,
  4,
  200,
  485,
  6,
  42,
  512,
  155,
  15,
  4,
  26,
  327,
  7,
  15,
  100,
  833,
  5,
  29,
  320,
  14,
  116,
  4877,
  5,
  2798,
  15,
  80,
  724,
  75,
  2535,
  12,
  6543,
  62,
  130,
  551,
  253,
  442,
  1457,
  39,
  76,
  12,
  26,
  529,
  24,
  75,
  309,
  1458,
  20,
  155,
  15],
 [853, 135, 426, 10162, 10163, 85, 6544, 854, 10164],
 [4878, 6, 198, 476, 19, 216, 248, 2, 17],
 [70, 32, 88, 135, 354, 6, 1166, 163, 287, 2166],
 [81,
  1121,
  2,
  99,
  180,
  171,
  4,
  21,
  13,
  175,
  3486,
  1587,
  398,
  6545,
  17,
  141,
  1260,
  1261,
  4879,
  4034],
 [2011, 4, 90, 5, 89, 2, 3104, 10165, 2167, 5, 125, 2, 82, 812, 152, 225],
 [438,
  2327,
  181,
  23,
  19,
  2,
  10166,
  1519,
  3,
  2327,
  1459,
  56,
  266,
  108,
  15,
  10167,
  4880,
  12,
  48,
  70,
  2168,
  56,
  10168,
  438,
  33],
 [923,
  10169,
  106,
  83,
  179,
  175,
  683,
  506,
  88,
  10170,
  2,
  6546,
  2169,
  10171,
  1885,
  1206,
  6547,
  96,
  84,
  144,
  1203,
  7,
  4881,
  2536,
  7,
  2,
  849,
  2328,
  10172,
  2537,
  4035,
  134,
  2799,
  23,
  10173,
  10174,
  10175,
  10176,
  10177,
  469],
 [6548,
  6549,
  22,
  89,
  2,
  901,
  725,
  834,
  26,
  5,
  167,
  10,
  193,
  250,
  10,
  2,
  2012,
  9,
  2,
  352,
  41,
  57,
  24,
  6,
  1207,
  74,
  141,
  5,
  2,
  250,
  4036,
  612],
 [19, 67, 6550, 47, 11],
 [9,
  6551,
  4882,
  875,
  7,
  288,
  2,
  6552,
  8,
  62,
  201,
  6,
  42,
  359,
  793,
  1460,
  2329,
  1007,
  9,
  1208,
  2330],
 [63],
 [140,
  9,
  13,
  297,
  24,
  3,
  541,
  4,
  275,
  6,
  332,
  3487,
  20,
  151,
  25,
  112,
  91,
  2,
  1886,
  241,
  8,
  140,
  9,
  708,
  114,
  876],
 [10178,
  2800,
  466,
  4,
  141,
  5,
  81,
  662,
  6,
  855,
  212,
  4,
  113,
  6,
  10179,
  10180,
  9,
  542,
  877,
  8,
  10181,
  40,
  6553,
  141,
  10182,
  53,
  1684,
  7,
  61,
  2170,
  12,
  8,
  14,
  794,
  6554,
  751,
  10183,
  10184,
  81,
  17,
  813,
  102,
  10185,
  157],
 [90,
  2801,
  4037,
  123,
  1775,
  1035,
  14,
  15,
  103,
  6555,
  5,
  31,
  77,
  320,
  37,
  103,
  5,
  15,
  29,
  123,
  107,
  902,
  167,
  10,
  304],
 [1685,
  2013,
  3488,
  4883,
  1887,
  451,
  121,
  10186,
  1776,
  6556,
  4884,
  479,
  1387,
  14,
  6557,
  530,
  10187],
 [13, 3489, 878, 10188, 57, 2538, 90],
 [11, 2, 176, 69, 298, 2539, 13, 69, 14, 317, 4038],
 [11, 28, 760, 338, 23, 150, 4, 1329, 13, 879],
 [48,
  6,
  178,
  18,
  943,
  6,
  178,
  18,
  1036,
  14,
  15,
  120,
  15,
  172,
  12,
  6,
  6558,
  3,
  213,
  4,
  172,
  4039,
  204,
  21,
  4885],
 [429, 429, 429, 429],
 [170, 52, 264, 417, 37, 507, 8, 2, 430, 232, 4, 38],
 [2802,
  10189,
  167,
  10,
  123,
  1167,
  4,
  486,
  924,
  202,
  2,
  178,
  4,
  101,
  48,
  15,
  356,
  6,
  360,
  79,
  709,
  303,
  663,
  1209,
  16,
  10,
  205,
  468,
  374,
  4,
  237,
  44,
  1262,
  95,
  726,
  39,
  10,
  6,
  237,
  240,
  106,
  10,
  1037,
  2803,
  880,
  2802,
  78,
  43,
  72,
  10190],
 [88,
  9,
  2,
  382,
  64,
  4886,
  7,
  191,
  7,
  168,
  8,
  20,
  2331,
  88,
  9,
  2,
  382,
  64,
  18,
  7,
  191,
  7,
  168,
  8,
  20,
  1330,
  88,
  9,
  2,
  382,
  64,
  4886,
  7,
  4040,
  7,
  168,
  8,
  20,
  2331,
  88,
  1888,
  2,
  382,
  64,
  4886,
  7,
  191,
  7,
  168,
  8,
  137,
  2331],
 [443, 881, 269, 248, 124, 412, 92, 1119, 3105, 2804, 1210, 4, 10191],
 [185, 460, 4, 21, 104, 121, 289, 61, 3, 58],
 [856,
  471,
  4,
  4041,
  5,
  1388,
  11,
  91,
  12,
  199,
  32,
  10192,
  8,
  87,
  226,
  1122,
  34,
  35,
  17,
  10193],
 [333, 124],
 [1076,
  7,
  6559,
  275,
  1777,
  1008,
  4,
  571,
  1389,
  354,
  45,
  45,
  6560,
  487,
  3490,
  7,
  448],
 [278,
  1390,
  3,
  58,
  36,
  83,
  1123,
  191,
  7,
  168,
  8,
  51,
  7,
  13,
  26,
  69,
  10194,
  83,
  3,
  22,
  58,
  12,
  182,
  374,
  3,
  243,
  357,
  1461,
  6,
  167,
  449],
 [579, 211, 12, 19, 2, 550, 408],
 [20, 622, 7, 13, 50, 6561, 6562, 4042],
 [2,
  176,
  814,
  7,
  380,
  168,
  28,
  6,
  1588,
  2540,
  10195,
  12,
  10196,
  78,
  72,
  10197],
 [944, 84, 21, 3106, 4, 23, 22, 971, 3, 89, 6, 79, 4043, 14],
 [8,
  835,
  258,
  312,
  186,
  945,
  129,
  613,
  835,
  267,
  4,
  138,
  795,
  7,
  2,
  128,
  6563,
  2014,
  5,
  260,
  170,
  2,
  443,
  426,
  761,
  14,
  258,
  223,
  277,
  34,
  1077,
  10198],
 [12, 8, 27, 2, 149, 69, 16, 2, 1009, 2541, 59, 1205, 323, 6, 1211],
 [4887, 155, 4044, 233, 3491, 14, 6564, 9, 2, 353, 288],
 [161,
  773,
  1778,
  29,
  468,
  82,
  4,
  96,
  562,
  3492,
  1038,
  403,
  9,
  30,
  603,
  85,
  6565],
 [262,
  56,
  238,
  270,
  628,
  3493,
  19,
  2,
  18,
  398,
  2805,
  4,
  24,
  6,
  2806,
  3494,
  318,
  3107,
  3495,
  4888,
  4889,
  4045,
  451,
  4890,
  383,
  2542,
  59,
  3108,
  326,
  31,
  3109,
  71,
  347,
  147,
  65,
  134,
  97,
  623,
  10199,
  115,
  2,
  258],
 [209,
  143,
  8,
  1779,
  9,
  1889,
  66,
  4,
  221,
  270,
  384,
  119,
  2171,
  9,
  11,
  92,
  812,
  74,
  6566,
  451,
  882],
 [836, 298, 4046, 2332],
 [41, 213, 6, 1212, 10, 404, 203, 444],
 [22,
  697,
  470,
  2807,
  186,
  2,
  1078,
  4,
  38,
  14,
  2,
  6567,
  76,
  10200,
  6,
  303,
  18,
  28,
  4,
  310,
  1462,
  6568,
  70,
  20,
  6569,
  4,
  101],
 [3,
  165,
  11,
  395,
  178,
  14,
  79,
  357,
  73,
  552,
  10,
  6,
  1391,
  4,
  237,
  508,
  534,
  79,
  9,
  18,
  480,
  10201],
 [129,
  98,
  9,
  11,
  227,
  212,
  438,
  1890,
  2,
  3496,
  752,
  186,
  46,
  601,
  75,
  16,
  232,
  11,
  333,
  134,
  445,
  2,
  18,
  55,
  15,
  49,
  22,
  384,
  14,
  6,
  6570,
  202,
  5,
  562,
  121,
  124,
  1520],
 [30,
  2,
  316,
  69,
  946,
  2,
  553,
  16,
  117,
  29,
  753,
  73,
  360,
  684,
  77,
  1263,
  1521,
  2,
  4891,
  752,
  175,
  7,
  131,
  63,
  27,
  24,
  645,
  4,
  592,
  837,
  5,
  63,
  27,
  24,
  645,
  4,
  592,
  425,
  231,
  175,
  7,
  131,
  63,
  27,
  24,
  645,
  4,
  592,
  425],
 [1392,
  117,
  8,
  52,
  3110,
  2796,
  2172,
  10,
  4047,
  4048,
  4892,
  6571,
  9,
  2,
  1780,
  2333,
  243,
  12,
  21,
  1124,
  16,
  10202,
  115,
  451,
  6572,
  97,
  972,
  2,
  383,
  7,
  2,
  2333,
  163,
  8,
  6573,
  71,
  125,
  186,
  4,
  2,
  1079,
  2326,
  1117,
  6574,
  159,
  1038,
  8,
  6575,
  664,
  135,
  6576,
  4049,
  4,
  361,
  219],
 [2],
 [56,
  9,
  6,
  513,
  878,
  7,
  710,
  203,
  39,
  25,
  3,
  24,
  4,
  200,
  12,
  28,
  1393,
  56,
  318,
  268,
  47,
  727,
  109,
  14,
  19,
  1125,
  203,
  39,
  3,
  328,
  51,
  128,
  477,
  21,
  6,
  387,
  7,
  12,
  26,
  61,
  6,
  6577,
  34,
  86,
  17,
  4893],
 [167, 262, 10, 1891, 23, 187, 6, 404, 18, 19, 53, 1331, 6578, 3111],
 [2, 87, 108, 761, 30, 2, 294, 7, 11, 8, 1891, 23],
 [1039,
  28,
  323,
  6,
  42,
  163,
  10,
  83,
  2543,
  196,
  217,
  85,
  6579,
  31,
  947,
  2173,
  64,
  2544,
  124,
  4050,
  31,
  318,
  773,
  392,
  198,
  6580,
  2174,
  6,
  1463,
  163],
 [148,
  514,
  148,
  393,
  22,
  1394,
  256,
  37,
  15,
  5,
  140,
  706,
  37,
  36,
  537,
  329,
  385,
  125,
  27,
  9,
  1168,
  63,
  3,
  38,
  4,
  1264,
  13,
  242,
  358,
  6581,
  11,
  8,
  815],
 [153,
  171,
  728,
  15,
  49,
  15,
  169,
  876,
  883,
  113,
  11,
  50,
  4894,
  18,
  394,
  2,
  4895,
  4896,
  1126,
  67,
  2545,
  2,
  762,
  18,
  838,
  74,
  16,
  26,
  3112,
  729,
  12,
  80,
  115,
  20,
  122,
  25,
  3,
  49,
  80,
  16,
  43,
  44,
  538],
 [730,
  26,
  1127,
  4,
  604,
  375,
  2,
  4051,
  86,
  629,
  5,
  108,
  4052,
  16,
  4897,
  33,
  145,
  373,
  77,
  451,
  10203,
  5,
  10204,
  126,
  614,
  11,
  8,
  133,
  774,
  1395,
  14,
  1686,
  102,
  834],
 [1589,
  452,
  48,
  15,
  29,
  27,
  554,
  4,
  731,
  3113,
  348,
  63,
  12,
  2015,
  903,
  36,
  4053,
  312,
  29,
  186,
  4054,
  677,
  25,
  15,
  38,
  224,
  37,
  3113,
  20,
  125,
  493],
 [472,
  413,
  10205,
  472,
  413,
  6582,
  61,
  2,
  2175,
  24,
  46,
  265,
  4,
  2,
  2334,
  6583,
  14,
  2,
  4898,
  10206,
  11,
  8,
  65,
  134,
  32,
  228,
  46,
  1590,
  19,
  311,
  16,
  1522,
  481,
  472,
  413,
  6582],
 [11,
  3497,
  8,
  142,
  3,
  58,
  1523,
  6584,
  630,
  19,
  2,
  1010,
  14,
  12,
  55,
  12,
  22,
  1121,
  4,
  200,
  16,
  13],
 [6585,
  22,
  450,
  116,
  64,
  37,
  13,
  3114,
  399,
  36,
  2335,
  652,
  652,
  49,
  80,
  14,
  43,
  754,
  139,
  4,
  181,
  310,
  2,
  499],
 [1524, 3, 49, 80, 43, 139, 10, 152, 13, 79, 2808],
 [79,
  177,
  22,
  1265,
  6,
  2160,
  605,
  23,
  216,
  6586,
  4055,
  17,
  141,
  1011,
  1261,
  2336],
 [61, 41, 58, 203, 39, 4056, 106, 1464, 283, 66, 95, 196],
 [159,
  69,
  400,
  44,
  10207,
  414,
  23,
  3,
  572,
  2,
  513,
  732,
  55,
  3,
  28,
  227,
  4,
  239,
  6587,
  2337,
  7,
  2,
  615,
  9,
  2,
  41,
  29,
  217,
  85,
  973,
  123,
  615,
  178,
  400,
  17,
  83,
  10208],
 [4899, 233, 42, 10, 2, 10209],
 [4, 6588, 3115, 9, 96, 84, 144, 31, 146, 118, 4057, 6589],
 [430, 2809, 10210, 4058, 175, 4900, 1266],
 [1267,
  408,
  82,
  305,
  1396,
  47,
  520,
  461,
  13,
  710,
  2338,
  15,
  112,
  82,
  1396,
  10,
  816,
  755,
  40,
  555,
  9,
  172,
  7,
  236,
  191,
  204,
  21,
  4901,
  4902],
 [85, 3, 58, 51, 198, 34, 35, 17, 6590],
 [61, 12, 200, 131, 453, 57, 2339, 19, 12, 195, 101, 12, 68, 170, 309, 66],
 [153,
  271,
  65,
  63,
  46,
  260,
  170,
  2,
  4059,
  665,
  624,
  32,
  6591,
  244,
  646,
  665,
  3,
  220,
  631,
  2176,
  4903,
  2176,
  578,
  775,
  32,
  252,
  403,
  37,
  51,
  2177,
  55,
  252,
  205,
  2,
  107,
  232,
  4,
  113,
  12,
  2178,
  8,
  4,
  359,
  1591,
  2,
  1592],
 [3,
  220,
  140,
  678,
  4904,
  4,
  774,
  2340,
  2179,
  1892,
  30,
  221,
  556,
  108,
  10,
  2016],
 [61, 6, 429, 128, 33, 3, 112, 139, 4, 725, 4060, 5, 44, 183, 7, 184],
 [370, 500],
 [923,
  6592,
  79,
  5,
  6593,
  66,
  430,
  6594,
  2795,
  10211,
  17,
  6595,
  3498,
  10212,
  6596,
  6597,
  66,
  10213,
  4061,
  10214,
  6598,
  6599,
  6600,
  1259],
 [6,
  10215,
  1268,
  6601,
  4,
  246,
  15,
  187,
  6,
  343,
  7,
  399,
  81,
  2546,
  539,
  10,
  267,
  4,
  6602,
  2,
  849,
  10216,
  9,
  36,
  723],
 [10217, 29, 2, 370, 241, 16, 49, 1525, 9, 6, 353, 288, 904, 6603, 5, 6604],
 [153, 182, 2180, 14, 170, 190, 2181, 521, 10218, 5, 67, 348, 24, 182],
 [3,
  110,
  6,
  285,
  62,
  69,
  4,
  44,
  2810,
  136,
  5,
  2,
  62,
  3,
  44,
  2,
  18,
  2,
  62,
  6605,
  3,
  111,
  16,
  11,
  18,
  8,
  2,
  227,
  234,
  241],
 [16, 2, 227, 1269, 57, 44, 87, 135],
 [217, 64, 1893, 5, 6, 217, 643, 4899, 21, 20, 284, 51, 128],
 [81, 10219, 419, 14, 756, 2547, 4, 2, 1462, 10220, 17, 81, 10221],
 [88,
  135,
  19,
  13,
  733,
  540,
  89,
  261,
  149,
  905,
  2182,
  354,
  23,
  5,
  67,
  299,
  201,
  356,
  80,
  43,
  857,
  60],
 [64, 94, 92, 18, 15, 89, 1593, 711, 113, 12, 34, 35, 17, 10222],
 [31,
  8,
  512,
  1894,
  40,
  3,
  208,
  58,
  2811,
  1895,
  137,
  188,
  3,
  601,
  165,
  105,
  7,
  131,
  121,
  16,
  685,
  51,
  199,
  974,
  748],
 [4062,
  1128,
  11,
  18,
  362,
  38,
  182,
  62,
  535,
  121,
  2,
  1465,
  53,
  1040,
  11,
  18,
  28,
  6,
  3499],
 [11,
  8,
  6,
  359,
  51,
  91,
  686,
  20,
  4063,
  3,
  57,
  357,
  4,
  6606,
  506,
  197,
  327,
  666,
  2341,
  6607,
  6608],
 [2, 82, 4905],
 [1041,
  173,
  266,
  21,
  20,
  6609,
  48,
  1397,
  74,
  852,
  6610,
  1213,
  14,
  2,
  1129,
  12,
  6611,
  430],
 [10223, 82, 580, 3116, 1781, 110, 2, 853, 679, 7, 70, 734, 735],
 [6612,
  876,
  1779,
  228,
  3,
  201,
  58,
  629,
  539,
  22,
  32,
  6613,
  5,
  6614,
  26,
  7,
  36,
  396,
  3,
  24,
  3,
  712,
  10224,
  5,
  3,
  58,
  12,
  32,
  3,
  58,
  228,
  3,
  6615,
  3,
  27,
  24,
  6,
  412,
  71,
  6,
  190,
  99,
  71,
  6,
  667,
  4064,
  3,
  107,
  3500,
  24,
  27,
  6,
  712,
  5,
  3,
  49,
  27,
  38,
  16,
  228,
  19,
  876,
  1779,
  12,
  3,
  3117,
  15,
  98,
  876],
 [1270, 223, 81, 975, 10225, 1782, 9, 366, 4906, 394, 2332, 17, 2017, 884],
 [364, 259, 58],
 [3, 111, 360, 111, 2342, 266, 776, 11, 166, 40, 431, 40, 12, 1169],
 [27, 107, 292, 86, 1594, 36, 839, 25, 70, 137, 92, 10, 2018],
 [6616,
  209,
  450,
  506,
  6,
  1012,
  7,
  116,
  64,
  18,
  454,
  2,
  250,
  4,
  1165,
  55,
  6617,
  4065,
  12,
  364,
  557,
  12],
 [1120,
  116,
  111,
  41,
  632,
  11,
  54,
  3118,
  98,
  10226,
  23,
  173,
  157,
  173,
  170,
  3119,
  231,
  2,
  383,
  1595,
  29,
  2812,
  46,
  1596,
  5,
  117,
  247,
  1332,
  26,
  630,
  65,
  8,
  11,
  6,
  241],
 [3501, 6618],
 [93, 593, 393, 135, 836, 298, 4907, 6619, 4066],
 [3, 57, 140, 678, 4904, 4, 774, 2340, 2179, 1892, 30, 108, 5, 215, 10, 2016],
 [88, 135, 8, 201, 2, 82, 130, 109, 4, 44, 10227, 9, 1597, 222],
 [2,
  1214,
  948,
  26,
  47,
  26,
  180,
  212,
  115,
  2813,
  212,
  39,
  2343,
  1264,
  1271,
  295,
  17,
  2164,
  177,
  99,
  141,
  78,
  43,
  72,
  6620],
 [687,
  6621,
  6622,
  10228,
  45,
  376,
  12,
  110,
  2178,
  1598,
  125,
  4067,
  355,
  713,
  6623,
  272,
  6624,
  78,
  43,
  72,
  6625],
 [11,
  177,
  47,
  2,
  114,
  4068,
  180,
  8,
  2,
  175,
  508,
  179,
  555,
  47,
  371,
  26,
  163,
  34,
  35,
  17,
  10229],
 [606,
  206,
  28,
  1170,
  757,
  10,
  494,
  4069,
  2,
  1042,
  600,
  5,
  2344,
  2,
  18,
  40,
  431,
  293,
  3,
  243,
  5,
  63,
  3,
  505,
  4908,
  1896,
  11,
  271,
  31],
 [2,
  633,
  387,
  8,
  16,
  117,
  29,
  239,
  62,
  10230,
  10231,
  130,
  3120,
  5,
  3120,
  244,
  6626,
  4,
  207,
  9,
  62,
  10232,
  6627,
  5,
  46,
  6628,
  102,
  26],
 [231,
  3,
  80,
  724,
  75,
  88,
  11,
  18,
  10,
  3502,
  2345,
  194,
  3,
  80,
  326,
  668,
  1599,
  7,
  12],
 [171, 81, 542, 976, 971, 3, 134, 24, 6, 321, 34, 35, 17, 10233],
 [6],
 [10234,
  8,
  13,
  3121,
  7,
  2019,
  6629,
  4909,
  2814,
  9,
  462,
  191,
  19,
  6,
  4070,
  10235,
  214,
  400,
  10236,
  129,
  613,
  835],
 [498, 1526, 2, 93, 60, 401, 41, 24, 6, 653, 4, 2346, 94, 34, 35, 17, 10237],
 [1327,
  124,
  572,
  20,
  15,
  24,
  137,
  240,
  645,
  4,
  796,
  7,
  92,
  81,
  531,
  15,
  49,
  310,
  19,
  55,
  36,
  885,
  37,
  103,
  127,
  2183,
  621,
  49,
  2548,
  26,
  15,
  62,
  9,
  289,
  22,
  16,
  257,
  171,
  272,
  3503],
 [4910,
  2815,
  15,
  346,
  348,
  425,
  25,
  49,
  15,
  63,
  98,
  98,
  181,
  858,
  33,
  119,
  398,
  219,
  5,
  152,
  977,
  414,
  153,
  3122,
  4,
  63,
  256,
  47,
  6630,
  91,
  95,
  623,
  43,
  23,
  46,
  29,
  289,
  364,
  304,
  98,
  181,
  102,
  46,
  634,
  80,
  1527,
  43,
  886,
  4,
  102,
  6,
  1466,
  32,
  23,
  244,
  8,
  594,
  439],
 [420,
  1215,
  495,
  205,
  421,
  65,
  11,
  900,
  2172,
  972,
  207,
  329,
  8,
  1130,
  27,
  6631],
 [12, 28, 3504, 100, 8, 2, 3505, 1272, 4071, 30, 16, 86],
 [2020, 854, 7, 43, 334],
 [48, 107, 2, 6632, 9, 2816, 218, 1216, 42],
 [501, 797, 79, 8, 109, 4, 93, 15, 19, 898],
 [81,
  925,
  39,
  3506,
  306,
  4072,
  121,
  2,
  1687,
  40,
  52,
  581,
  2,
  2817,
  1013,
  272,
  6633,
  78,
  72,
  6634],
 [3507,
  17,
  2021,
  1467,
  6635,
  4911,
  470,
  4073,
  4912,
  11,
  582,
  2549,
  926,
  2550,
  3,
  22,

In [151]:
from keras.utils import pad_sequences

In [152]:
sequences=pad_sequences(sequences,padding='pre')

In [153]:
sequences

array([[    0,     0,     0, ...,    95,   196,  2523],
       [    0,     0,     0, ...,     7,  2160,  3095],
       [    0,     0,     0, ...,     0,     0,    51],
       ...,
       [    0,     0,     0, ...,    20,   222,  6161],
       [    0,     0,     0, ...,    43,    72, 17872],
       [    0,     0,     0, ...,   784,  1025,  6485]], dtype=int32)

## Without the Embedding layer

In [155]:
from tensorflow.keras.layers import SimpleRNN,Dense, Input,Embedding
from tensorflow.keras.models import Sequential

In [156]:
X=sequences

In [157]:
y=data['Sentiment'].values

In [158]:
X

array([[    0,     0,     0, ...,    95,   196,  2523],
       [    0,     0,     0, ...,     7,  2160,  3095],
       [    0,     0,     0, ...,     0,     0,    51],
       ...,
       [    0,     0,     0, ...,    20,   222,  6161],
       [    0,     0,     0, ...,    43,    72, 17872],
       [    0,     0,     0, ...,   784,  1025,  6485]], dtype=int32)

In [159]:
y

array([2, 0, 2, ..., 0, 1, 2])

In [160]:
from sklearn.model_selection import train_test_split

In [161]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [162]:
X_train.shape

(9493, 99)

In [165]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(99,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))

c:\Users\adity\miniconda3\envs\HealthConnect\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [167]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [168]:
from keras.src.metrics import metric
model.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [169]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 4s 12ms/step - accuracy: 0.3570 - loss: 1.1209 - val_accuracy: 0.3597 - val_loss: 1.0911
Epoch 2/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 9ms/step - accuracy: 0.3638 - loss: 1.0958 - val_accuracy: 0.3559 - val_loss: 1.0906
Epoch 3/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3739 - loss: 1.0923 - val_accuracy: 0.3618 - val_loss: 1.0894
Epoch 4/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.3715 - loss: 1.0941 - val_accuracy: 0.3589 - val_loss: 1.0898
Epoch 5/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.3568 - loss: 1.0960 - val_accuracy: 0.3568 - val_loss: 1.0940
Epoch 6/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 3s 19ms/step - accuracy: 0.3683 - loss: 1.0921 - val_accuracy: 0.3652 - val_loss: 1.0894
Epoch 7/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.3684 - loss: 1.0913 - val_accuracy: 0.3623 - val_loss: 1.0895
Epoch 8/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.3754 - loss: 1.0912 - val_accuracy: 0.3580 - val_loss: 1.0882
Epoch 9/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.3574 - loss: 1.0925 - val_accuracy: 0.3551 - val_loss: 1.0914
Epoch 10/10
149/149 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3753 - loss: 1.0939 - val_accuracy: 0.3576 - val_loss: 1.0906

## With Embedding layer

In [170]:
vocab_size=len(tokenizer.word_index)+1

In [171]:
vocab_size

17873

In [173]:
model_2=Sequential()
model_2.add(Input(shape=(99,)))
model_2.add(Embedding(input_dim=vocab_size,output_dim=64))
model_2.add(Dense(3,activation='softmax'))

In [174]:
model_2.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (None, 99, 64)         │     1,143,872 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 99, 3)          │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,144,067 (4.36 MB)

 Trainable params: 1,144,067 (4.36 MB)

 Non-trainable params: 0 (0.00 B)

In [175]:
model_final=Sequential([Embedding(input_dim=vocab_size,output_dim=128,input_length=99,mask_zero=True),
SimpleRNN(32),Dense(3,activation='softmax')])

c:\Users\adity\miniconda3\envs\HealthConnect\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [176]:
model_final.compile(optimizer='adam',metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [177]:
model_final.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [181]:
model_final.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/100

149/149 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.9915 - loss: 0.0255 - val_accuracy: 0.7131 - val_loss: 1.0516
Epoch 2/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.9921 - loss: 0.0176 - val_accuracy: 0.7127 - val_loss: 1.0713
Epoch 3/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.9909 - loss: 0.0192 - val_accuracy: 0.7148 - val_loss: 1.1023
Epoch 4/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.9929 - loss: 0.0142 - val_accuracy: 0.7190 - val_loss: 1.1270
Epoch 5/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 3s 21ms/step - accuracy: 0.9932 - loss: 0.0145 - val_accuracy: 0.7195 - val_loss: 1.1526
Epoch 6/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 5s 36ms/step - accuracy: 0.9926 - loss: 0.0156 - val_accuracy: 0.7161 - val_loss: 1.1665
Epoch 7/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9926 - loss: 0.0145 - val_accuracy: 0.7186 - val_loss: 1.1921
Epoch 8/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9937 - loss: 0.0149 - val_accuracy: 0.7165 - val_loss: 1.1992
Epoch 9/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 39ms/step - accuracy: 0.9927 - loss: 0.0136 - val_accuracy: 0.7190 - val_loss: 1.2090
Epoch 10/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9906 - loss: 0.0160 - val_accuracy: 0.7157 - val_loss: 1.2448
Epoch 11/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9923 - loss: 0.0133 - val_accuracy: 0.7190 - val_loss: 1.2400
Epoch 12/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9928 - loss: 0.0141 - val_accuracy: 0.7102 - val_loss: 1.2678
Epoch 13/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9931 - loss: 0.0120 - val_accuracy: 0.7148 - val_loss: 1.2789
Epoch 14/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9935 - loss: 0.0122 - val_accuracy: 0.7089 - val_loss: 1.3032
Epoch 15/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9930 - loss: 0.0127 - val_accuracy: 0.7144 - val_loss: 1.3054
Epoch 16/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9924 - loss: 0.0141 - val_accuracy: 0.7077 - val_loss: 1.3281
Epoch 17/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 38ms/step - accuracy: 0.9931 - loss: 0.0126 - val_accuracy: 0.7157 - val_loss: 1.3476
Epoch 18/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9927 - loss: 0.0130 - val_accuracy: 0.7131 - val_loss: 1.3355
Epoch 19/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9921 - loss: 0.0137 - val_accuracy: 0.7123 - val_loss: 1.3413
Epoch 20/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9924 - loss: 0.0127 - val_accuracy: 0.7136 - val_loss: 1.3411
Epoch 21/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9929 - loss: 0.0128 - val_accuracy: 0.7051 - val_loss: 1.3723
Epoch 22/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9933 - loss: 0.0125 - val_accuracy: 0.7013 - val_loss: 1.4090
Epoch 23/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9916 - loss: 0.0148 - val_accuracy: 0.7148 - val_loss: 1.3929
Epoch 24/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9926 - loss: 0.0123 - val_accuracy: 0.7136 - val_loss: 1.4088
Epoch 25/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9939 - loss: 0.0115 - val_accuracy: 0.7072 - val_loss: 1.4228
Epoch 26/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9927 - loss: 0.0128 - val_accuracy: 0.7072 - val_loss: 1.4315
Epoch 27/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9932 - loss: 0.0131 - val_accuracy: 0.7022 - val_loss: 1.4473
Epoch 28/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9940 - loss: 0.0113 - val_accuracy: 0.7089 - val_loss: 1.4620
Epoch 29/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9949 - loss: 0.0104 - val_accuracy: 0.7035 - val_loss: 1.4785
Epoch 30/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9930 - loss: 0.0128 - val_accuracy: 0.6963 - val_loss: 1.4652
Epoch 31/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9925 - loss: 0.0134 - val_accuracy: 0.7018 - val_loss: 1.4955
Epoch 32/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9939 - loss: 0.0120 - val_accuracy: 0.7005 - val_loss: 1.4859
Epoch 33/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 39ms/step - accuracy: 0.9938 - loss: 0.0105 - val_accuracy: 0.6967 - val_loss: 1.5236
Epoch 34/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9929 - loss: 0.0114 - val_accuracy: 0.6828 - val_loss: 1.5518
Epoch 35/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9948 - loss: 0.0104 - val_accuracy: 0.6874 - val_loss: 1.5341
Epoch 36/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9842 - loss: 0.0393 - val_accuracy: 0.6609 - val_loss: 1.3434
Epoch 37/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9697 - loss: 0.0801 - val_accuracy: 0.6921 - val_loss: 1.2060
Epoch 38/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9912 - loss: 0.0222 - val_accuracy: 0.7115 - val_loss: 1.1863
Epoch 39/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9940 - loss: 0.0139 - val_accuracy: 0.7081 - val_loss: 1.2224
Epoch 40/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9912 - loss: 0.0149 - val_accuracy: 0.7110 - val_loss: 1.2370
Epoch 41/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9937 - loss: 0.0123 - val_accuracy: 0.7119 - val_loss: 1.2566
Epoch 42/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 38ms/step - accuracy: 0.9928 - loss: 0.0135 - val_accuracy: 0.7136 - val_loss: 1.2719
Epoch 43/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9925 - loss: 0.0136 - val_accuracy: 0.7136 - val_loss: 1.2892
Epoch 44/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 39ms/step - accuracy: 0.9928 - loss: 0.0117 - val_accuracy: 0.7136 - val_loss: 1.3037
Epoch 45/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9941 - loss: 0.0117 - val_accuracy: 0.7115 - val_loss: 1.3193
Epoch 46/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9941 - loss: 0.0119 - val_accuracy: 0.7131 - val_loss: 1.3238
Epoch 47/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9938 - loss: 0.0106 - val_accuracy: 0.7148 - val_loss: 1.3351
Epoch 48/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9929 - loss: 0.0122 - val_accuracy: 0.7148 - val_loss: 1.3522
Epoch 49/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9935 - loss: 0.0110 - val_accuracy: 0.7157 - val_loss: 1.3519
Epoch 50/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9928 - loss: 0.0114 - val_accuracy: 0.7131 - val_loss: 1.3677
Epoch 51/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9941 - loss: 0.0108 - val_accuracy: 0.7115 - val_loss: 1.3760
Epoch 52/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9921 - loss: 0.0131 - val_accuracy: 0.7119 - val_loss: 1.3915
Epoch 53/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9935 - loss: 0.0120 - val_accuracy: 0.7136 - val_loss: 1.3910
Epoch 54/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9929 - loss: 0.0115 - val_accuracy: 0.7119 - val_loss: 1.4004
Epoch 55/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9930 - loss: 0.0122 - val_accuracy: 0.7127 - val_loss: 1.4159
Epoch 56/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9937 - loss: 0.0116 - val_accuracy: 0.7115 - val_loss: 1.4259
Epoch 57/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9929 - loss: 0.0125 - val_accuracy: 0.7094 - val_loss: 1.4226
Epoch 58/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9935 - loss: 0.0105 - val_accuracy: 0.7110 - val_loss: 1.4416
Epoch 59/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9927 - loss: 0.0124 - val_accuracy: 0.7144 - val_loss: 1.4558
Epoch 60/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9933 - loss: 0.0126 - val_accuracy: 0.7098 - val_loss: 1.4720
Epoch 61/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9933 - loss: 0.0120 - val_accuracy: 0.7136 - val_loss: 1.4670
Epoch 62/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9925 - loss: 0.0127 - val_accuracy: 0.7060 - val_loss: 1.4709
Epoch 63/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9922 - loss: 0.0140 - val_accuracy: 0.7060 - val_loss: 1.4868
Epoch 64/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9937 - loss: 0.0107 - val_accuracy: 0.7089 - val_loss: 1.4977
Epoch 65/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9946 - loss: 0.0108 - val_accuracy: 0.7030 - val_loss: 1.5088
Epoch 66/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9931 - loss: 0.0124 - val_accuracy: 0.7060 - val_loss: 1.5157
Epoch 67/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9932 - loss: 0.0126 - val_accuracy: 0.7035 - val_loss: 1.5217
Epoch 68/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9934 - loss: 0.0110 - val_accuracy: 0.7009 - val_loss: 1.5112
Epoch 69/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9926 - loss: 0.0114 - val_accuracy: 0.7005 - val_loss: 1.5441
Epoch 70/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9916 - loss: 0.0130 - val_accuracy: 0.7030 - val_loss: 1.5407
Epoch 71/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9921 - loss: 0.0133 - val_accuracy: 0.6950 - val_loss: 1.5749
Epoch 72/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9944 - loss: 0.0114 - val_accuracy: 0.7030 - val_loss: 1.5729
Epoch 73/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9937 - loss: 0.0107 - val_accuracy: 0.6988 - val_loss: 1.5892
Epoch 74/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9936 - loss: 0.0106 - val_accuracy: 0.6942 - val_loss: 1.5927
Epoch 75/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9924 - loss: 0.0148 - val_accuracy: 0.6807 - val_loss: 1.4611
Epoch 76/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9836 - loss: 0.0425 - val_accuracy: 0.6912 - val_loss: 1.4187
Epoch 77/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9918 - loss: 0.0174 - val_accuracy: 0.7056 - val_loss: 1.3688
Epoch 78/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9946 - loss: 0.0110 - val_accuracy: 0.7085 - val_loss: 1.3826
Epoch 79/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9939 - loss: 0.0106 - val_accuracy: 0.7089 - val_loss: 1.3940
Epoch 80/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9923 - loss: 0.0121 - val_accuracy: 0.7119 - val_loss: 1.4037
Epoch 81/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9927 - loss: 0.0119 - val_accuracy: 0.7110 - val_loss: 1.4123
Epoch 82/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 40ms/step - accuracy: 0.9913 - loss: 0.0133 - val_accuracy: 0.7123 - val_loss: 1.4177
Epoch 83/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9930 - loss: 0.0118 - val_accuracy: 0.7119 - val_loss: 1.4259
Epoch 84/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9934 - loss: 0.0113 - val_accuracy: 0.7119 - val_loss: 1.4356
Epoch 85/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9933 - loss: 0.0119 - val_accuracy: 0.7140 - val_loss: 1.4402
Epoch 86/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9942 - loss: 0.0097 - val_accuracy: 0.7131 - val_loss: 1.4466
Epoch 87/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9942 - loss: 0.0098 - val_accuracy: 0.7098 - val_loss: 1.4543
Epoch 88/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9942 - loss: 0.0106 - val_accuracy: 0.7136 - val_loss: 1.4592
Epoch 89/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 39ms/step - accuracy: 0.9922 - loss: 0.0124 - val_accuracy: 0.7089 - val_loss: 1.4767
Epoch 90/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9927 - loss: 0.0121 - val_accuracy: 0.7119 - val_loss: 1.4753
Epoch 91/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9931 - loss: 0.0121 - val_accuracy: 0.7110 - val_loss: 1.4819
Epoch 92/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9926 - loss: 0.0130 - val_accuracy: 0.7110 - val_loss: 1.4854
Epoch 93/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 39ms/step - accuracy: 0.9936 - loss: 0.0128 - val_accuracy: 0.7110 - val_loss: 1.4936
Epoch 94/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 40ms/step - accuracy: 0.9914 - loss: 0.0148 - val_accuracy: 0.7110 - val_loss: 1.5000
Epoch 95/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9943 - loss: 0.0096 - val_accuracy: 0.7115 - val_loss: 1.4999
Epoch 96/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 7s 44ms/step - accuracy: 0.9936 - loss: 0.0107 - val_accuracy: 0.7102 - val_loss: 1.5142
Epoch 97/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 7s 43ms/step - accuracy: 0.9920 - loss: 0.0121 - val_accuracy: 0.7094 - val_loss: 1.5175
Epoch 98/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 10s 43ms/step - accuracy: 0.9922 - loss: 0.0112 - val_accuracy: 0.7102 - val_loss: 1.5223
Epoch 99/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9937 - loss: 0.0098 - val_accuracy: 0.7098 - val_loss: 1.5354
Epoch 100/100
149/149 ━━━━━━━━━━━━━━━━━━━━ 6s 43ms/step - accuracy: 0.9932 - loss: 0.0120 - val_accuracy: 0.7094 - val_loss: 1.5393

In [179]:
import pickle

In [180]:
with open('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [183]:
model_final.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.